/** 
 * Tag: string, array, bit
 * 
 * ---------------------------------------------
 * Given two strings s and t which consist of only lowercase letters.
 * 
 * String t is generated by random shuffling string s and then add 
 * one more letter at a random position.
 * Find the letter that was added in t.
 * 
 * Example: Input: s = "abcd", t = "abcde"
 * Output: e
 * Explanation: 'e' is the letter that was added.
 --------------------------------------------- */
 
package leetcode.algorithms.P3xx;

import static org.junit.Assert.assertTrue;

public class P389_FindTheDifference {

    /* ---------------------------------------------
     * Simple O(n) solution
     * --------------------------------------------- */
    public static char findTheDifference_1(String s, String t) {
        int freq[] = new int[26];
        int n = s.length();
        freq[t.charAt(n) - 'a']--;
        for (int i = 0; i < n; i++) {
            freq[s.charAt(i) - 'a']++;
            freq[t.charAt(i) - 'a']--;
        }
        for (int i = 0; i < t.length(); i++) {
            if (freq[i] != 0)
                return (char) (i + 'a');
        }
        return 0;
    }

    /* ---------------------------------------------
     * using bit manipulation
     * --------------------------------------------- */
    public static char findTheDifference_2(String s, String t) {
        char c = 0;
        for (int i = 0; i < s.length(); ++i) {
            c ^= s.charAt(i);
        }
        for (int i = 0; i < t.length(); ++i) {
            c ^= t.charAt(i);
        }
        return c;
    }

    /* ---------------------------------------------
     * better version
     * --------------------------------------------- */
    public static char findTheDifference_3(String s, String t) {
        int n = t.length();
        char c = t.charAt(n - 1);
        for (int i = 0; i < n - 1; ++i) {
            c ^= s.charAt(i);
            c ^= t.charAt(i);
        }
        return c;
    }

    public static char findTheDifference(String s, String t) {
        return findTheDifference_2(s, t);
    }

    public static void main(String[] args) {
        assertTrue("Test1", findTheDifference("abcd", "abcde") == 'e');
        assertTrue("Test1", findTheDifference("abcd", "aebcd") == 'e');
        assertTrue("Test1", findTheDifference("abcd", "eabcd") == 'e');
        System.out.println("All Tests passed");
    }
}
